credentials:
  usernames:
    alaw:
      email: andylaw0811@gmail.com
      name: Andy Law
      password: '$2b$12$KouQvYYreNjehCrVaErRJ.vgcz1fZmeIMN5PYTdk9LSF9cgl5lKrS'
cookie:
  expiry_days: 0
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com