[cookie]
expiry_days = 0
key = "some_signature_key"
name = "some_cookie_name"

[credentials]
usernames = {alaw = {email = "andylaw0811@gmail.com", name = "Andy Law", password = "$2b$12$KouQvYYreNjehCrVaErRJ.vgcz1fZmeIMN5PYTdk9LSF9cgl5lKrS"}, jsmith = {email = "jsmith@gmail.com", name = "John Smith", password = "$2b$12$L035ey6vkdHW6523PDg24ezWgKB2mEeI7ARaonKcLoXNOg6wtCGc."}}

[preauthorized]
emails = ["256melsby@gmail.com"]